project:
  type: website
  output-dir: docs

website:
  title: "Jessi Rumkin"
  favicon: j-favicon.png
  search: 
    location: navbar
    type: overlay
  navbar:
    title: FALSE
    logo: j-favicon.png
    logo-alt: "lowercase j image"
    left:
      - href: index.qmd
        text: Jessi Rumkin - Home
      - href: about.qmd
        text: About Me
      - posts.qmd
      - text: "Education Highlights"
        menu: 
          - UCSB-enviro.qmd
          - UCSB-GIS.qmd
          - Netherlands-Edu.qmd
      - text: Resume
        href: general_resume.pdf
        target: "_blank"
    right: 
      - text: "Contact and Other links"
        menu: 
          - icon: envelope
            text: Open email client
            href: mailto:jrumkin@ucsb.edu
          - icon: envelope
            text: "jrumkin@ucsb.edu"
          - icon: linkedin
            text: "LinkedIn"
            href: https://www.linkedin.com/in/jessica-rumkin-80b59129a/
          - icon: github
            text: "GitHub"
            href: https://github.com/jrumkin


format:
  html:
    theme: 
      - Yeti
      - style.scss
    mainfont: Reddit Sans
    toc: true
    page-layout: full

editor: visual

