project:
  type: website
  output-dir: docs

website:
  title: "Jessi Rumkin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Projects and Portfolios.qmd

format:
  html:
    backgroundcolor: "#FCF9F3"
    theme: lumen
    css: styles.css
    toc: true

editor: visual

