project:
  type: website
  output-dir: docs

website:
  title: "Jessi Rumkin"
  favicon: j-favicon.png
  navbar:
    title: FALSE
    logo: j-favicon.png
    logo-alt: "lowercase j image"
    left:
      - href: index.qmd
        text: Jessi Rumkin - Home
      - about.qmd
      - posts.qmd
      - text: "Education Highlights"
        menu: 
          - UCSB-enviro.qmd
          - UCSB-GIS.qmd
          - Netherlands-Edu.qmd
      - Resume.qmd

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

