project:
  type: website
  output-dir: docs

website:
  title: "Jessi Rumkin"
  navbar:
    title: FALSE
    left:
      - href: index.qmd
        text: Jessi Rumkin - Home
      - about.qmd
      - posts.qmd
      - text: "Education Highlights"
        menu: 
          - UCSB-enviro.qmd
          - UCSB-GIS.qmd
          - Netherlands-Edu.qmd

format:
  html:
    backgroundcolor: "#FCF9F3"
    theme: lumen
    css: styles.css
    toc: true

editor: visual

