---
title: "Bren Environmental Studies Fellowship"
description: A professional development fellowship to link UCSB environmental studies students to the Bren envrironmental graduate school.
author: "Jessi Rumkin"
date: 05-28-2025
categories: [UCSB, Bren]
format: html
---

The Bren Environmental Studies Fellowship is a partnership between UCSB's Environmental Studies department and the Bren graduate school on UCSB campus.

See [here](https://bren.ucsb.edu/undergrad-mentoring/bren-es-fellows-program/bren-es-fellows/jessi-rumkin#:~:text=Jessi%20Rumkin-,Jessi%20Rumkin,-Bren%2DEnvironmental%20Studies "Open in browser") for my participant bio, and [here](https://bren.ucsb.edu/undergrad-mentoring/bren-es-fellows-program#:~:text=ENVIRONMENTAL%20STUDIES%20FELLOWS-,PROGRAM%20OVERVIEW,-Developed%20by%20the "Open in browser") for more program information.

------------------------------------------------------------------------

Being accepted into this fellowship opened opportunties that helped me further my professional and academic development. Being a part of the Educational Opportunity Program at UCSB as a first generation college student has come with its challenges, but the community and support from the other fellows helped me face and grow from them.

The fellowship created structured opportunities to work on networking skills, resume writing, meet with faculty, and set up mentor meetings with Bren students, faculty, and field professionals.

A special thanks to the Program Director, Heather Stanford, for all her hard work in managing the program and always being in my corner.
